#!/usr/bin/env python3
"""The Markdown backend: API reference + documentation index, from the model.

⛔ VENDORED. Byte-identical copy of spec2si-flowkit's `docs/mdbackend.py`,
hash-gated by that repo's `sync.py --check`. Edit it THERE, never here.

THE FIRST OF THREE BACKENDS, and the reason `docmodel.py` was split out at
all. It renders what `DocModel` parsed; it does no parsing of its own. The
web manual and the PDF are the other two, and they will hang off the SAME
model -- which is the whole point, because a second extractor would be a
second thing to keep in step and would drift the moment one of them was
taught something the other was not.

⚠ WHAT IS AND IS NOT REPO-SPECIFIC. Everything here is generic given a
CONFIG: the areas and their globs, where docs live, what the DO-NOT-EDIT
header should say. That config stays in each repo's `docs/gen.py`, along
with any card it renders from its own machine-read JSON. Rendering does not:
three repos rendering three slightly different API pages is exactly the
divergence `docmeta.core.json` was created to stop, one level up.

⚠ STDLIB ONLY -- see the note in docmodel.py. The freshness gate runs in CI
with no PDK, no licence and no dependency install, and that is load-bearing.
"""
import os

import docmodel

DEFAULT_HEADER = ("<!-- GENERATED by docs/gen.py -- DO NOT EDIT. "
                  "Run `python docs/gen.py build`. -->\n")


class MarkdownBackend(object):
    """Render one repo's docs to Markdown, in place.

    `model` is a `docmodel.DocModel`; `docsdir` is the repo's docs/ tree;
    `areas` is a list of (name, description, globs) in READING ORDER, which
    is the order the API reference and the index will use.
    """

    def __init__(self, model, docsdir, areas, header=None, refdir=None,
                 index=None):
        self.model = model
        self.docsdir = docsdir
        self.areas = list(areas)
        self.header = DEFAULT_HEADER if header is None else header
        self.refdir = refdir or os.path.join(docsdir, "reference")
        self.index = index or os.path.join(docsdir, "INDEX.md")

    def build_api(self):
        """Write <refdir>/api/<area>.md for each area. Return summary."""
        m = self.model
        apidir = os.path.join(self.refdir, "api")
        os.makedirs(apidir, exist_ok=True)
        totals = {}
        for area, desc, globs in self.areas:
            files = m.iter_py(globs)
            L = [self.header, "# API reference — `{}`\n".format(area),
                 "_{}_\n".format(desc),
                 "Extracted statically from {} module(s). Public functions "
                 "and classes only.\n".format(len(files))]
            nfun = ncls = 0
            for path in files:
                api = docmodel.module_api(path)
                if api is None:
                    continue
                mdoc, funcs, classes = api
                if not funcs and not classes:
                    continue
                L.append("\n## `{}`".format(m.rel(path)))
                if docmodel.first_para(mdoc):
                    L.append("\n{}\n".format(docmodel.first_para(mdoc)))
                for sig, doc in funcs:
                    nfun += 1
                    L.append("- **`{}`**{}".format(
                        sig, " — " + docmodel.first_para(doc) if doc else ""))
                for name, cdoc, meths in classes:
                    ncls += 1
                    L.append("- **`class {}`**{}".format(
                        name,
                        " — " + docmodel.first_para(cdoc) if cdoc else ""))
                    for sig, doc in meths:
                        L.append("    - `{}`{}".format(
                            sig,
                            " — " + docmodel.first_para(doc) if doc else ""))
            out = os.path.join(apidir, area + ".md")
            m.write_if_changed(out, "\n".join(L).rstrip() + "\n")
            totals[area] = (len(files), nfun, ncls)
        return totals

    def build_index(self):
        """Write the documentation index from frontmatter. -> (tagged, untagged)"""
        m = self.model
        tagged, untagged = [], []
        for p, meta, body in m.iter_docs():
            if meta.get("genre"):
                tagged.append((p, meta))
            else:
                untagged.append(p)
        L = [self.header, "# Documentation index\n",
             "Every hand-authored doc, grouped by area then genre, built "
             "from frontmatter. See [docs/README.md](README.md) for the "
             "genre contracts.\n"]
        # group by area, then genre
        by_area = {}
        for p, meta in tagged:
            by_area.setdefault(meta.get("area", "misc"), []).append((p, meta))
        for area in sorted(by_area):
            L.append("\n## {}\n".format(area))
            L.append("| Doc | Genre | Status | Updated | Summary |")
            L.append("|-----|-------|--------|---------|---------|")
            rows = sorted(
                by_area[area],
                key=lambda pm: (m.genres.index(m.canon_genre(pm[1]["genre"]))
                                if m.canon_genre(pm[1]["genre"]) else 99,
                                pm[0]))
            for p, meta in rows:
                L.append("| [{}]({}) | {} | {} | {} | {} |".format(
                    meta.get("title", os.path.basename(p)),
                    os.path.relpath(p, self.docsdir).replace(os.sep, "/"),
                    meta.get("genre", "?"), meta.get("status", "?"),
                    meta.get("updated", "?"), meta.get("summary", "")))
        if untagged:
            L.append("\n## Untagged — needs frontmatter ({})\n".format(
                len(untagged)))
            L.append("_These are not yet in the index. Add a frontmatter "
                     "block (see docs/README.md) to file them._\n")
            for p in sorted(untagged):
                L.append("- `{}`".format(m.rel(p)))
        m.write_if_changed(self.index, "\n".join(L).rstrip() + "\n")
        return len(tagged), len(untagged)

    # -- orchestration reporting ---------------------------------------
    #
    # The BUILD is per-repo (tsmc65 renders cards from its own JSON that the
    # siblings do not have), but the REPORT is not, and a report is exactly
    # the kind of thing that drifts unnoticed: three repos printing three
    # slightly different pass lines is how you stop being able to compare
    # them. So the orchestration stays in each gen.py and the printing lives
    # here, taking what that orchestration found.

    def report_build(self, api, tagged, untagged):
        """Print the build summary. -> exit code."""
        tf = sum(v[1] for v in api.values())
        tc = sum(v[2] for v in api.values())
        print("built: API {} funcs / {} classes across {} areas; "
              "index {} tagged (+{} untagged)".format(
                  tf, tc, len(api), tagged, untagged))
        if self.model.dirty:
            print("  updated: " + ", ".join(self.model.dirty))
        else:
            print("  (all generated outputs already current)")
        return 0

    def report_check(self, problems, links, fm_bad, warn, aliased):
        """Print the gate result. -> exit code (1 = FAIL)."""
        m = self.model
        fail = bool(problems) or bool(links) or bool(fm_bad)
        if problems:
            print("STALE generated output (run `python docs/gen.py build`):")
            for x in problems:
                print("  - " + x)
        for x in links:
            print("DEAD LINK  " + x)
        for x in fm_bad:
            print("FRONTMATTER  " + x)
        if aliased:
            print("alias genre(s) in use (accepted; prefer the canonical "
                  "id): " + ", ".join(
                      "{}->{} x{}".format(g, m.canon_genre(g), n)
                      for g, n in sorted(aliased.items())))
        print("docs check: {} — {} untagged doc(s) (warn), {} link "
              "issue(s), {} frontmatter issue(s)".format(
                  "FAIL" if fail else "PASS", warn, len(links), len(fm_bad)))
        return 1 if fail else 0
