#!/usr/bin/env python3
"""The PDF manual backend: a curated LaTeX book, from the same model.

⛔ VENDORED. Byte-identical copy of spec2si-flowkit's `docs/texbackend.py`,
hash-gated by that repo's `sync.py --check`. Edit it THERE, never here.

⭐ THIS IS THE *METHOD* MANUAL, NOT A CHIP MANUAL. Decided deliberately: the
per-chip datasheets are hand-written LaTeX with a different cadence and a
different reader, and they stay exactly where they are. What is generated
here is the flow -- what the policy is, how a gate works, how to add a
process node -- assembled from the documents that already say it.

⚠ AND IT IS CURATED, WHICH IS THE POINT. The corpus is 176 documents and
most of them are session narrative: logs, studies, findings, plans. Those
are worth keeping and worth reading on the web, and they are worth nothing
in a bound manual that goes stale the moment it is printed. So the PDF takes
the genres whose CONTRACT is to stay true -- overview, guide, reference,
decision -- and leaves the rest to the site.

`decision` is in that list on purpose: a method manual without its decision
records omits the reasoning that makes it a method rather than a procedure.
The plan named overview/guide/reference before `decision` existed as a genre.
"""
import os

import docmodel
import texrender

#: The genres whose contract is to stay true. Everything else is a record of
#: a moment, and belongs on the web where it can be dated rather than bound.
PRINT_GENRES = ("overview", "guide", "reference", "decision")

PREAMBLE = r"""%% GENERATED by docs/gen.py -- DO NOT EDIT.
%% Build:  xelatex -interaction=nonstopmode <this file>   (twice, for the TOC)
\documentclass[10pt,a4paper,oneside]{report}

\usepackage[margin=22mm,includefoot]{geometry}
\usepackage{fontspec}
\usepackage{longtable}
\usepackage{array}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage[hidelinks,breaklinks]{hyperref}
\usepackage{newunicodechar}

%% ---- fonts -------------------------------------------------------------
%% XeLaTeX, because the structural markers and the units are not ASCII.
%% A font WITHOUT coverage drops the glyph silently, so test_pdf.py reads
%% the log for `Missing character` and fails the build on one.
\setmainfont{%(mainfont)s}
\setmonofont{%(monofont)s}[Scale=0.86]

%% ---- the three structural markers --------------------------------------
%% They are how these documents distinguish a prohibition from a note, so
%% they get typeset meaning rather than a glyph the font may not carry.
\definecolor{stopred}{HTML}{B3261E}
\definecolor{warnamber}{HTML}{A15C07}
\definecolor{starblue}{HTML}{3730A3}
\newcommand{\stopmark}{\textcolor{stopred}{\textbf{[STOP]}}}
\newcommand{\warnmark}{\textcolor{warnamber}{\textbf{[!]}}}
\newcommand{\starmark}{\textcolor{starblue}{\textbf{[*]}}}
\definecolor{okgreen}{HTML}{1B8A3F}
\newcommand{\okmark}{\textcolor{okgreen}{\textbf{[OK]}}}
\newcommand{\failmark}{\textcolor{stopred}{\textbf{[FAIL]}}}
\newcommand{\pausemark}{\textbf{[PAUSED]}}
\newcommand{\nextmark}{\textbf{[NEXT]}}
\newcommand{\chartmark}{\textbf{[chart]}}

\setlength{\parindent}{0pt}
\setlength{\parskip}{5pt plus 1pt}
\setlength{\emergencystretch}{3em}
\sloppy

\titleformat{\chapter}[hang]{\LARGE\bfseries}{\thechapter.}{0.6em}{}
\titlespacing*{\chapter}{0pt}{0pt}{14pt}

\pagestyle{fancy}\fancyhf{}
\renewcommand{\headrulewidth}{0.4pt}
\fancyhead[L]{\footnotesize %(title)s}
\fancyhead[R]{\footnotesize\leftmark}
\fancyfoot[C]{\footnotesize\thepage}
\fancyfoot[R]{\scriptsize %(notice)s}

\hypersetup{pdftitle={%(title)s},pdfauthor={%(author)s}}
\begin{document}
\begin{titlepage}\centering\vspace*{3cm}
{\Huge\bfseries %(title)s}\\[10pt]
{\Large %(subtitle)s}\\[26pt]
{\large %(author)s}\\[6pt]
{\small Generated from the repository by \texttt{docs/gen.py} on %(date)s}\\[4pt]
{\small %(counts)s}
\vfill
{\footnotesize %(notice)s}
\end{titlepage}
\tableofcontents
"""


class TexBackend(object):
    """Assemble one repo's method manual as a single .tex file."""

    def __init__(self, model, docsdir, areas, outdir, title, subtitle="",
                 author="", notice="", genres=PRINT_GENRES,
                 mainfont="DejaVu Sans", monofont="DejaVu Sans Mono"):
        self.model = model
        self.docsdir = docsdir
        self.areas = list(areas)
        self.outdir = outdir
        self.title = title
        self.subtitle = subtitle
        self.author = author
        self.notice = notice
        self.genres = tuple(genres)
        self.mainfont = mainfont
        self.monofont = monofont

    def _selected(self):
        """The documents that go in the book, in area then genre order."""
        recs = []
        for p, meta, body in self.model.iter_docs():
            g = self.model.canon_genre(meta.get("genre")) or ""
            if g not in self.genres:
                continue
            recs.append({"rel": self.model.rel(p), "meta": meta, "body": body,
                         "genre": g, "area": meta.get("area", "misc"),
                         "title": meta.get("title")
                         or os.path.basename(self.model.rel(p))})
        order = dict((a, k) for k, (a, _d, _g) in enumerate(self.areas))
        recs.sort(key=lambda r: (order.get(r["area"], 99), r["area"],
                                 self.genres.index(r["genre"]),
                                 r["title"].lower()))
        return recs

    def build(self, date="", codemap=True):
        recs = self._selected()
        skipped = self._skipped_count()
        counts = ("%d document(s) of %d -- %s only; the rest are on the web "
                  "manual" % (len(recs), len(recs) + skipped,
                              "/".join(self.genres)))
        head = PREAMBLE % {
            "title": _plain(self.title), "subtitle": _plain(self.subtitle),
            "author": _plain(self.author), "notice": _plain(self.notice),
            "date": _plain(date), "counts": _plain(counts),
            "mainfont": self.mainfont, "monofont": self.monofont}
        L = [head]
        area = None
        for r in recs:
            if r["area"] != area:
                area = r["area"]
                L.append(chr(10) + r"\part{%s}" % texrender.esc(area) + chr(10))
            L.append(chr(10) + r"\chapter{%s}" % texrender.esc(r["title"])
                     + chr(10))
            L.append(r"\label{doc:%s}" % _label(r["rel"]) + chr(10))
            m = r["meta"]
            L.append(r"{\small\textit{%s \textbullet{} %s \textbullet{} "
                     r"updated %s}}\par\vspace{4pt}" % (
                         texrender.esc(r["genre"]),
                         texrender.esc(m.get("status", "?")),
                         texrender.esc(m.get("updated", "?"))) + chr(10))
            body, _heads = texrender.render(r["body"], top=1,
                                            prefix=_label(r["rel"]) + ":")
            L.append(body)
        if codemap:
            L.append(self._codemap())
        L.append(chr(10) + r"\end{document}" + chr(10))
        out = os.path.join(self.outdir, "manual.tex")
        self.model.write_if_changed(out, "".join(L))
        return out, len(recs), skipped

    def _skipped_count(self):
        n = 0
        for _p, meta, _b in self.model.iter_docs():
            g = self.model.canon_genre(meta.get("genre")) or ""
            if g not in self.genres:
                n += 1
        return n

    def _codemap(self):
        """An appendix that MAPS the code rather than reproducing it.

        ⚠ Deliberately module summaries only, not every symbol. The full
        docstrings are 781 K -- right for a paginated web page and absurd in
        a bound appendix, where nobody looks up a signature anyway. What
        print is good for is telling you which file to open.
        """
        L = [chr(10) + r"\appendix" + chr(10),
             r"\chapter{Map of the code}" + chr(10),
             chr(10) + texrender.esc(
                 "One line per module, extracted by static AST parse. "
                 "Signatures and full docstrings are in the web manual; what "
                 "this appendix answers is which file to open.") + chr(10)]
        for name, desc, globs in self.areas:
            files = self.model.iter_py(globs)
            rows = []
            for path in files:
                got = docmodel.module_api(path)
                if got is None:
                    continue
                mdoc, funcs, classes = got
                if not funcs and not classes:
                    continue
                rows.append([self.model.rel(path),
                             docmodel.first_line(mdoc) or ""])
            if not rows:
                continue
            L.append(chr(10) + r"\section{%s}" % texrender.esc(name) + chr(10))
            L.append(chr(10) + texrender.esc(desc) + chr(10))
            e = texrender.LatexEmitter()
            L.append(e.table(["Module", "What it is"], rows, ["", ""]))
        return "".join(L)


def _plain(s):
    return texrender.esc(s or "")


def _label(rel):
    out = []
    for ch in rel:
        out.append(ch if ch.isalnum() else "-")
    return "".join(out)
