#!/usr/bin/env python3
"""The PDF manual backend: how-to chapters plus a generated reference.

⛔ VENDORED. Byte-identical copy of spec2si-flowkit's `docs/texbackend.py`,
hash-gated by that repo's `sync.py --check`. Edit it THERE, never here.

⭐ THIS WAS A TRANSCRIPT AND IS NOW A MANUAL. The first version bound 123
existing documents -- overview, guide, reference AND decision -- and the
result read exactly like what it was: a memoir of how the flow came to be,
not a book you can do anything with. Decisions are an append-only ADR
archive; overviews link out; findings and logs narrate a moment. Binding
narration does not produce instruction.

The repo's own genre contract had already said what a manual is:

    guide      hand-written and meant to be stable; POINTS AT generated
               reference rather than copying it
    reference  GENERATED, never hand-edited; cannot go stale by
               construction because a gate regenerates it

So the book is those two and nothing else. Part I is the how-to layer, in
the author's own words. Part II is the part a reader LOOKS THINGS UP in,
generated from the code: every runnable command, every public symbol with
its full signature, and an alphabetical index to find them by name.

⚠ THE ARCHIVE IS NOT DELETED, IT IS RELOCATED. Decisions, studies,
findings and logs stay in the web manual, where they can be dated and
browsed. What they are not is chapters of a manual.
"""

import os

import apiref
import docmodel
import texrender

#: ⛔ ONLY `guide`. The how-to layer is hand-written and stable by its own
#: contract; the reference half of the book is GENERATED below rather than
#: collected from documents. `overview` links out, `decision` is an
#: append-only archive, and `log`/`study`/`finding` narrate a moment --
#: none of them is a chapter, and binding them is what made the first
#: version a transcript.
PRINT_GENRES = ("guide",)

PREAMBLE = r"""%% GENERATED by docs/gen.py -- DO NOT EDIT.
%% Build:  xelatex -interaction=nonstopmode <this file>   (twice, for the TOC)
\documentclass[10pt,a4paper,oneside]{report}

\usepackage[margin=22mm,includefoot]{geometry}
\usepackage{fontspec}
\usepackage{longtable}
\usepackage{array}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage[hidelinks,breaklinks]{hyperref}
\usepackage{multicol}
\usepackage{newunicodechar}

%% ---- fonts -------------------------------------------------------------
%% XeLaTeX, because the structural markers and the units are not ASCII.
%% A font WITHOUT coverage drops the glyph silently, so test_pdf.py reads
%% the log for `Missing character` and fails the build on one.
\setmainfont{%(mainfont)s}
\setmonofont{%(monofont)s}[Scale=0.86]

%% ---- the three structural markers --------------------------------------
%% They are how these documents distinguish a prohibition from a note, so
%% they get typeset meaning rather than a glyph the font may not carry.
\definecolor{stopred}{HTML}{B3261E}
\definecolor{warnamber}{HTML}{A15C07}
\definecolor{starblue}{HTML}{3730A3}
\newcommand{\stopmark}{\textcolor{stopred}{\textbf{[STOP]}}}
\newcommand{\warnmark}{\textcolor{warnamber}{\textbf{[!]}}}
\newcommand{\starmark}{\textcolor{starblue}{\textbf{[*]}}}
\definecolor{okgreen}{HTML}{1B8A3F}
\newcommand{\okmark}{\textcolor{okgreen}{\textbf{[OK]}}}
\newcommand{\failmark}{\textcolor{stopred}{\textbf{[FAIL]}}}
\newcommand{\pausemark}{\textbf{[PAUSED]}}
\newcommand{\nextmark}{\textbf{[NEXT]}}
\newcommand{\chartmark}{\textbf{[chart]}}

\setlength{\parindent}{0pt}
\setlength{\parskip}{5pt plus 1pt}
\setlength{\emergencystretch}{3em}
\sloppy

\titleformat{\chapter}[hang]{\LARGE\bfseries}{\thechapter.}{0.6em}{}
\titlespacing*{\chapter}{0pt}{0pt}{14pt}

\pagestyle{fancy}\fancyhf{}
\renewcommand{\headrulewidth}{0.4pt}
\fancyhead[L]{\footnotesize %(title)s}
\fancyhead[R]{\footnotesize\leftmark}
\fancyfoot[C]{\footnotesize\thepage}
\fancyfoot[R]{\scriptsize %(notice)s}

\hypersetup{pdftitle={%(title)s},pdfauthor={%(author)s}}
\begin{document}
\begin{titlepage}\centering\vspace*{3cm}
{\Huge\bfseries %(title)s}\\[10pt]
{\Large %(subtitle)s}\\[26pt]
{\large %(author)s}\\[6pt]
{\small Generated from the repository by \texttt{docs/gen.py} on %(date)s}\\[4pt]
{\small %(counts)s}
\vfill
{\footnotesize %(notice)s}
\end{titlepage}
\tableofcontents
"""


class TexBackend(object):
    """Assemble one repo's method manual as a single .tex file."""

    def __init__(self, model, docsdir, areas, outdir, title, subtitle="",
                 author="", notice="", genres=PRINT_GENRES,
                 mainfont="DejaVu Sans", monofont="DejaVu Sans Mono"):
        self.model = model
        self.docsdir = docsdir
        self.areas = list(areas)
        self.outdir = outdir
        self.title = title
        self.subtitle = subtitle
        self.author = author
        self.notice = notice
        self.genres = tuple(genres)
        self.mainfont = mainfont
        self.monofont = monofont

    def _selected(self):
        """The documents that go in the book, in area then genre order."""
        recs = []
        for p, meta, body in self.model.iter_docs():
            g = self.model.canon_genre(meta.get("genre")) or ""
            if g not in self.genres:
                continue
            recs.append({"rel": self.model.rel(p), "meta": meta, "body": body,
                         "genre": g, "area": meta.get("area", "misc"),
                         "title": meta.get("title")
                         or os.path.basename(self.model.rel(p))})
        order = dict((a, k) for k, (a, _d, _g) in enumerate(self.areas))
        recs.sort(key=lambda r: (order.get(r["area"], 99), r["area"],
                                 self.genres.index(r["genre"]),
                                 r["title"].lower()))
        return recs

    def _skipped_count(self):
        """How many documents are deliberately NOT chapters.

        Printed in the manual rather than passed over: a reader who cannot
        find the ADRs should be told they exist and where, not left to
        assume the flow has no recorded decisions."""
        n = 0
        for _p, meta, _b in self.model.iter_docs():
            g = self.model.canon_genre(meta.get("genre")) or ""
            if g not in self.genres:
                n += 1
        return n

    def build(self, date="", codemap=True):
        """Write the manual. -> (path, how-to chapters, skipped documents)."""
        recs = self._selected()
        skipped = self._skipped_count()
        cmds = apiref.commands(self.model, self.areas)
        syms = apiref.symbols(self.model, self.areas)
        mods = apiref.modules(self.model, self.areas)
        documented, total = apiref.coverage(cmds)
        counts = ("%d how-to chapter(s); reference covers %d command(s) and "
                  "%d public symbol(s) in %d module(s)"
                  % (len(recs), total, len(syms), len(mods)))
        head = PREAMBLE % {
            "title": _plain(self.title), "subtitle": _plain(self.subtitle),
            "author": _plain(self.author), "notice": _plain(self.notice),
            "date": _plain(date), "counts": _plain(counts),
            "mainfont": self.mainfont, "monofont": self.monofont}
        L = [head]
        L.append(self._howto(recs, skipped))
        L.append(self._reference(cmds, mods, documented, total))
        L.append(self._index(syms))
        L.append(chr(10) + r"\end{document}" + chr(10))
        out = os.path.join(self.outdir, "manual.tex")
        self.model.write_if_changed(out, "".join(L))
        return out, len(recs), skipped

    # -- part I: the how-to layer --------------------------------------

    def _howto(self, recs, skipped):
        L = [chr(10) + r"\part{How to}" + chr(10),
             chr(10) + texrender.esc(
                 "Hand-written procedures. These are the only chapters not "
                 "generated from the code, and by their own contract they "
                 "point at the reference in Part II rather than restate it. "
                 "%d other document(s) in this repository are decisions, "
                 "studies, findings or logs: they record how things came to "
                 "be, are kept in the web manual, and are deliberately not "
                 "chapters here." % skipped) + chr(10)]
        for r in recs:
            L.append(chr(10) + r"\chapter{%s}" % texrender.esc(r["title"])
                     + chr(10))
            m = r["meta"]
            L.append(r"{\small\textit{%s \textbullet{} updated %s}}"
                     r"\par\vspace{4pt}" % (
                         texrender.esc(r["rel"]),
                         texrender.esc(m.get("updated", "?"))) + chr(10))
            body, _h = texrender.render(r["body"], top=1,
                                        prefix=_label(r["rel"]) + ":")
            L.append(body)
        return "".join(L)

    # -- part II: the generated reference ------------------------------

    def _reference(self, cmds, mods, documented, total):
        L = [chr(10) + r"\part{Reference}" + chr(10),
             chr(10) + texrender.esc(
                 "Generated from the source by static parse. Nothing here is "
                 "hand-written, so it cannot disagree with the code.")
             + chr(10)]
        L.append(self._commands(cmds, documented, total))
        L.append(self._api(mods))
        return "".join(L)

    def _commands(self, cmds, documented, total):
        """Every runnable entry point: what it is, and how it is invoked."""
        L = [chr(10) + r"\chapter{Commands}" + chr(10),
             chr(10) + texrender.esc(
                 "%d runnable entry point(s). %d carry a usage line in their "
                 "module docstring and %d do not -- that gap is printed "
                 "rather than hidden, because an undocumented command and a "
                 "documented one look identical from the outside until you "
                 "count." % (total, documented, total - documented))
             + chr(10)]
        area = None
        for c in cmds:
            if c["area"] != area:
                area = c["area"]
                L.append(chr(10) + r"\section{%s}" % texrender.esc(area)
                         + chr(10))
            L.append(chr(10) + r"\subsection*{\texttt{\small %s}}"
                     % texrender._tt(c["module"]) + chr(10))
            if c["summary"]:
                L.append(texrender.esc(c["summary"]) + chr(10))
            if c["usage"]:
                e = texrender.LatexEmitter()
                L.append(e.code(c["usage"], ""))
            else:
                L.append(chr(10) + r"{\small\textit{%s}}" % texrender.esc(
                    "No usage line in the module docstring.") + chr(10))
        return "".join(L)

    def _api(self, mods):
        """Every public symbol, with its FULL signature.

        ⚠ Signatures in full, summaries to one paragraph. A reference is
        consulted for the CALL -- the argument you forgot, the return shape --
        and truncating a signature defeats the only question it is asked. The
        prose is trimmed instead, and the web manual carries it whole.
        """
        L = [chr(10) + r"\chapter{API}" + chr(10)]
        area = None
        for m in mods:
            if m["area"] != area:
                area = m["area"]
                L.append(chr(10) + r"\section{%s}" % texrender.esc(area)
                         + chr(10))
            L.append(chr(10) + r"\subsection*{\texttt{\small %s}}"
                     % texrender._tt(m["module"]) + chr(10))
            L.append(r"\label{mod:%s}" % _label(m["module"]) + chr(10))
            if m["doc"]:
                L.append(chr(10) + texrender.esc(
                    docmodel.first_para(m["doc"])) + chr(10))
            for sig, doc in m["funcs"]:
                L.append(self._entry(m["module"], sig, doc))
            for name, cdoc, meths in m["classes"]:
                L.append(self._entry(m["module"], "class " + name, cdoc))
                for sig, doc in meths:
                    L.append(self._entry(m["module"], sig, doc, indent=True))
        return "".join(L)

    @staticmethod
    def _entry(module, sig, doc, indent=False):
        pre = r"\hspace*{1.2em}" if indent else ""
        L = [chr(10) + r"\vspace{3pt}\noindent %s\texttt{\small\textbf{%s}}"
             r"\par" % (pre, texrender._tt(sig)) + chr(10)]
        if doc:
            L.append(r"\vspace{1pt}{\small %s%s}\par" % (
                pre, texrender.esc(docmodel.first_para(doc))) + chr(10))
        return "".join(L)

    # -- part III: the index -------------------------------------------

    def _index(self, syms):
        r"""Alphabetical symbol index -- the thing that makes it a reference.

        ⚠ Built by hand rather than with `makeidx`, which would need a
        second tool (`makeindex`) in the build. Page numbers come from
        `\pageref` against the per-module labels, which is why the manual
        needs two XeLaTeX passes.
        """
        idx = apiref.index(syms)
        L = [chr(10) + r"\appendix" + chr(10),
             r"\chapter{Index of symbols}" + chr(10),
             chr(10) + texrender.esc(
                 "%d distinct public name(s). A name defined in more than one "
                 "module lists each, because that is the question an index is "
                 "actually asked." % len(idx)) + chr(10),
             chr(10) + r"{\footnotesize\raggedright" + chr(10),
             r"\begin{multicols}{2}" + chr(10)]
        letter = None
        for name, places in idx:
            first = name[0].upper() if name else "?"
            if first != letter:
                letter = first
                L.append(chr(10) + r"\textbf{%s}\par" % texrender.esc(letter)
                         + chr(10))
            where = ", ".join(
                r"\texttt{%s}~p.\pageref{mod:%s}" % (
                    texrender._tt(os.path.basename(mod)), _label(mod))
                for mod, _k, _p in places[:4])
            L.append(r"\texttt{%s} --- %s\par" % (
                texrender._tt(name), where) + chr(10))
        L.append(r"\end{multicols}}" + chr(10))
        return "".join(L)


def _plain(s):
    return texrender.esc(s or "")


def _label(rel):
    out = []
    for ch in rel:
        out.append(ch if ch.isalnum() else "-")
    return "".join(out)
